### ISSUE TITLE
Intent to close

### ISSUE THREAD

**Issue by miekg** [coredns/dynapi#2]
this repository seems not go anywhere. I intent to delete this repo at some pont

**Comment by mrueg** [comment]
@syndbg any plans to continue here?

**Comment by syndbg** [comment]
@mrueg Sorry for the lack of activity from my side.

I believe that I can still continue it. 

Due to poor health, I haven't had the time to commit to the project.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/dynapi] Intent to clos..." ]
>@mrueg Sorry for the lack of activity from my side.
>
>I believe that I can still continue it.
>
>Due to poor health, I haven't had the time to commit to the project.

Sad to hear about your health.

There is no rush, but I'm trying to clean up thingss, we can always move some 
personal repo of yours into this once things have reached a certain staged.
